
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "superduper-core"
version = "0.0.10"
description = "Superdupper core."
readme = "README.md"

[tool.setuptools.packages.find]
include = ["superdupper.core"]
